# -*- coding: utf-8 -*-
"""mles assignment.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vW2Q82W6sLjYOHyqt_WT0SEV7CqiplIE
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ultralytics/yolov5.git
# %cd yolov5
!pip install -r requirements.txt

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="mMIkoyyQac5Y6TsWxdNl")
project = rf.workspace("kabam").project("garbage-detection-bnn5b")
version = project.version(2)
dataset = version.download("yolov5")

!python train.py --img 460 --batch 32 --epochs 100 --data garbage-detection-2/data.yaml --weights yolov5s.pt